### PR TITLE
add support for List<String> fields

### PR DESCRIPTION
**Pull request by Yarikx**

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks for that, looks good!
the only thing is that if you pass a `LinkedList<String>` in you will get an `ArrayList<String>` out, but I guess that's fine and no simple workaround for that as it's the default behaviour of `Parcel`

**Comment by Yarikx** [comment]
Yes, you are right.
But I think it can be solved by only supporting List<String> and ArrayList<String> (as `parcel.createStringArrayList()` return `ArrayList`)

What do you think about it?

**Comment by sockeqwe** [comment]
I think it's fine as it's is for now, since also `readStringList()`
> returns: A newly created ArrayList containing strings with the same data as those that were previously written.

So Parcel internally uses `ArrayList` anyway. But that's fine. If you really have to ensure that same kind of list is restored you can provide your own implementation by using `@Bagger` i.e. `LinkedListBagger`

**Comment by Yarikx** [comment]
Ok, will leave it for now without further type restriction

**Pull request merged**
